package com.mini.venta.entities;

// Generated Jan 15, 2013 11:21:45 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "AREA")
public class Area implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long idArea;
	private String nombre;
	private Set<Cargo> cargos = new HashSet<Cargo>(0);
	private Set<Empleado> empleados = new HashSet<Empleado>(0);

	public Area() {
	}

	public Area(String nombre, Set<Cargo> cargos, Set<Empleado> empleados) {
		this.nombre = nombre;
		this.cargos = cargos;
		this.empleados = empleados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_AREA", unique = true, nullable = false)
	public Long getIdArea() {
		return this.idArea;
	}

	public void setIdArea(Long idArea) {
		this.idArea = idArea;
	}

	@Column(name = "NOMBRE", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "area")
	public Set<Cargo> getCargos() {
		return this.cargos;
	}

	public void setCargos(Set<Cargo> cargos) {
		this.cargos = cargos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

	@Override
	public String toString() {
		return getNombre();
	}
}
