package com.mini.venta.entities;

// Generated Jan 15, 2013 11:21:45 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Credito generated by hbm2java
 */
@Entity
@Table(name = "CREDITO")
public class Credito implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long idCredito;
	private Venta venta;
	private BigDecimal saldo;
	private BigDecimal limite;
	private Date fechaLimite;
	private Character estado;
	private Integer nroCoutas;
	private Set<DetallePago> detallePagos = new HashSet<DetallePago>(0);

	public Credito() {
	}

	public Credito(Venta venta) {
		this.venta = venta;
	}

	public Credito(Venta venta, BigDecimal saldo, BigDecimal limite,
			Date fechaLimite, Character estado, Integer nroCoutas,
			Set<DetallePago> detallePagos) {
		this.venta = venta;
		this.saldo = saldo;
		this.limite = limite;
		this.fechaLimite = fechaLimite;
		this.estado = estado;
		this.nroCoutas = nroCoutas;
		this.detallePagos = detallePagos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_CREDITO", unique = true, nullable = false)
	public Long getIdCredito() {
		return this.idCredito;
	}

	public void setIdCredito(Long idCredito) {
		this.idCredito = idCredito;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_VENTA", nullable = false)
	public Venta getVenta() {
		return this.venta;
	}

	public void setVenta(Venta venta) {
		this.venta = venta;
	}

	@Column(name = "SALDO", precision = 10)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@Column(name = "LIMITE", precision = 10)
	public BigDecimal getLimite() {
		return this.limite;
	}

	public void setLimite(BigDecimal limite) {
		this.limite = limite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_LIMITE", length = 19)
	public Date getFechaLimite() {
		return this.fechaLimite;
	}

	public void setFechaLimite(Date fechaLimite) {
		this.fechaLimite = fechaLimite;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "NRO_COUTAS")
	public Integer getNroCoutas() {
		return this.nroCoutas;
	}

	public void setNroCoutas(Integer nroCoutas) {
		this.nroCoutas = nroCoutas;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "credito")
	public Set<DetallePago> getDetallePagos() {
		return this.detallePagos;
	}

	public void setDetallePagos(Set<DetallePago> detallePagos) {
		this.detallePagos = detallePagos;
	}

}
