package com.mini.venta.entities;

// Generated Jan 15, 2013 11:21:45 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "DEPARTAMENTO")
public class Departamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long idDepartamento;
	private String coddpto;
	private String nombre;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Departamento() {
	}

	public Departamento(String coddpto) {
		this.coddpto = coddpto;
	}

	public Departamento(String coddpto, String nombre, Set<Cliente> clientes) {
		this.coddpto = coddpto;
		this.nombre = nombre;
		this.clientes = clientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_DEPARTAMENTO", unique = true, nullable = false)
	public Long getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(Long idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	@Column(name = "CODDPTO", nullable = false, length = 2)
	public String getCoddpto() {
		return this.coddpto;
	}

	public void setCoddpto(String coddpto) {
		this.coddpto = coddpto;
	}

	@Column(name = "NOMBRE", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	@Override
	public String toString() {
		return getNombre();
	}
	
}
