package com.mini.venta.entities;

// Generated Jan 15, 2013 11:21:45 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleSueldo generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_SUELDO")
public class DetalleSueldo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long idDetalleSueldo;
	private Empleado empleado;
	private BigDecimal sueldo;
	private BigDecimal gratificacion;
	private Date fecha;
	private BigDecimal descuento;
	private BigDecimal sueldoNeto;

	public DetalleSueldo() {
	}

	public DetalleSueldo(Empleado empleado) {
		this.empleado = empleado;
	}

	public DetalleSueldo(Empleado empleado, BigDecimal sueldo,
			BigDecimal gratificacion, Date fecha, BigDecimal descuento,
			BigDecimal sueldoNeto) {
		this.empleado = empleado;
		this.sueldo = sueldo;
		this.gratificacion = gratificacion;
		this.fecha = fecha;
		this.descuento = descuento;
		this.sueldoNeto = sueldoNeto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_DETALLE_SUELDO", unique = true, nullable = false)
	public Long getIdDetalleSueldo() {
		return this.idDetalleSueldo;
	}

	public void setIdDetalleSueldo(Long idDetalleSueldo) {
		this.idDetalleSueldo = idDetalleSueldo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_EMPLEADO", nullable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "SUELDO", precision = 6)
	public BigDecimal getSueldo() {
		return this.sueldo;
	}

	public void setSueldo(BigDecimal sueldo) {
		this.sueldo = sueldo;
	}

	@Column(name = "GRATIFICACION", precision = 6)
	public BigDecimal getGratificacion() {
		return this.gratificacion;
	}

	public void setGratificacion(BigDecimal gratificacion) {
		this.gratificacion = gratificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "DESCUENTO", precision = 3)
	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	@Column(name = "SUELDO_NETO", precision = 6)
	public BigDecimal getSueldoNeto() {
		return this.sueldoNeto;
	}

	public void setSueldoNeto(BigDecimal sueldoNeto) {
		this.sueldoNeto = sueldoNeto;
	}

}
