package com.mini.venta.entities;

// Generated Jan 15, 2013 11:21:45 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "EMPLEADO")
public class Empleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long idEmpleado;
	private Cargo cargo;
	private Area area;
	private String nombre;
	private String apellido;
	private String dni;
	private String telefono;
	private String EMail;
	private String direccion;
	private String usuario;
	private String password;
	private Character estado;
	private String celular;
	private Set<DetalleSueldo> detalleSueldos = new HashSet<DetalleSueldo>(0);
	private Set<Corte> cortes = new HashSet<Corte>(0);
	private Set<Venta> ventas = new HashSet<Venta>(0);

	public Empleado() {
	}

	public Empleado(Cargo cargo, Area area) {
		this.cargo = cargo;
		this.area = area;
	}

	public Empleado(Cargo cargo, Area area, String nombre, String apellido,
			String dni, String telefono, String EMail, String direccion,
			String usuario, String password, Character estado, String celular,
			Set<DetalleSueldo> detalleSueldos, Set<Corte> cortes,
			Set<Venta> ventas) {
		this.cargo = cargo;
		this.area = area;
		this.nombre = nombre;
		this.apellido = apellido;
		this.dni = dni;
		this.telefono = telefono;
		this.EMail = EMail;
		this.direccion = direccion;
		this.usuario = usuario;
		this.password = password;
		this.estado = estado;
		this.celular = celular;
		this.detalleSueldos = detalleSueldos;
		this.cortes = cortes;
		this.ventas = ventas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_EMPLEADO", unique = true, nullable = false)
	public Long getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(Long idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_CARGO", nullable = false)
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_AREA", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@Column(name = "NOMBRE", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "APELLIDO", length = 50)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "DNI", length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "TELEFONO", length = 7)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "E_MAIL", length = 50)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	@Column(name = "DIRECCION", length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "USUARIO", length = 18)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "PASSWORD", length = 18)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "CELULAR", length = 9)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleado")
	public Set<DetalleSueldo> getDetalleSueldos() {
		return this.detalleSueldos;
	}

	public void setDetalleSueldos(Set<DetalleSueldo> detalleSueldos) {
		this.detalleSueldos = detalleSueldos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleado")
	public Set<Corte> getCortes() {
		return this.cortes;
	}

	public void setCortes(Set<Corte> cortes) {
		this.cortes = cortes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleado")
	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}

}
