package com.mini.venta.entities;

// Generated Jan 15, 2013 11:21:45 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "MARCA")
public class Marca implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long idMarca;
	private String nombre;
	private Set<Modelo> modelos = new HashSet<Modelo>(0);
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Marca() {
	}

	public Marca(String nombre, Set<Modelo> modelos, Set<Producto> productos) {
		this.nombre = nombre;
		this.modelos = modelos;
		this.productos = productos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_MARCA", unique = true, nullable = false)
	public Long getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(Long idMarca) {
		this.idMarca = idMarca;
	}

	@Column(name = "NOMBRE", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "marca")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

	@Override
	public String toString() {
		return getNombre();
	}
}
