package com.mini.venta.entities;

// Generated Jan 15, 2013 11:21:45 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPago generated by hbm2java
 */
@Entity
@Table(name = "TIPO_PAGO")
public class TipoPago implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long idTipoPago;
	private String descripcion;
	private Set<Venta> ventas = new HashSet<Venta>(0);

	public TipoPago() {
	}

	public TipoPago(String descripcion, Set<Venta> ventas) {
		this.descripcion = descripcion;
		this.ventas = ventas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_TIPO_PAGO", unique = true, nullable = false)
	public Long getIdTipoPago() {
		return this.idTipoPago;
	}

	public void setIdTipoPago(Long idTipoPago) {
		this.idTipoPago = idTipoPago;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPago")
	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}

	@Override
	public String toString() {
		return getDescripcion();
	}
}
