package com.mini.venta.entities;

// Generated Jan 15, 2013 11:21:45 AM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name = "VENTA")
public class Venta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long idVenta;
	private Empleado empleado;
	private NotaPedido notaPedido;
	private Moneda moneda;
	private TipoPago tipoPago;
	private Date fecha;
	private BigDecimal tipoCambio;
	private Date fechaEntrega;
	private String direccionEntrega;
	private Set<Credito> creditos = new HashSet<Credito>(0);

	public Venta() {
	}

	public Venta(Empleado empleado, NotaPedido notaPedido,
			Moneda moneda, TipoPago tipoPago, Date fecha) {
		this.empleado = empleado;
		this.notaPedido = notaPedido;
		this.moneda = moneda;
		this.tipoPago = tipoPago;
		this.fecha = fecha;
	}

	public Venta(Empleado empleado, NotaPedido notaPedido,
			Moneda moneda, TipoPago tipoPago, Date fecha,
			BigDecimal tipoCambio, Date fechaEntrega, String direccionEntrega,
			Set<Credito> creditos) {
		this.empleado = empleado;
		this.notaPedido = notaPedido;
		this.moneda = moneda;
		this.tipoPago = tipoPago;
		this.fecha = fecha;
		this.tipoCambio = tipoCambio;
		this.fechaEntrega = fechaEntrega;
		this.direccionEntrega = direccionEntrega;
		this.creditos = creditos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_VENTA", unique = true, nullable = false)
	public Long getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(Long idVenta) {
		this.idVenta = idVenta;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_EMPLEADO", nullable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_NPEDIDO", nullable = false)
	public NotaPedido getNotaPedido() {
		return this.notaPedido;
	}

	public void setNotaPedido(NotaPedido notaPedido) {
		this.notaPedido = notaPedido;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_MONEDA", nullable = false)
	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_TIPO_PAGO", nullable = false)
	public TipoPago getTipoPago() {
		return this.tipoPago;
	}

	public void setTipoPago(TipoPago tipoPago) {
		this.tipoPago = tipoPago;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "TIPO_CAMBIO", precision = 3)
	public BigDecimal getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(BigDecimal tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_ENTREGA", length = 19)
	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	@Column(name = "DIRECCION_ENTREGA", length = 100)
	public String getDireccionEntrega() {
		return this.direccionEntrega;
	}

	public void setDireccionEntrega(String direccionEntrega) {
		this.direccionEntrega = direccionEntrega;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "venta")
	public Set<Credito> getCreditos() {
		return this.creditos;
	}

	public void setCreditos(Set<Credito> creditos) {
		this.creditos = creditos;
	}

}
